### PR TITLE
Flask Documentation

### PR DESCRIPTION
**Pull request by karantatiwala**

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
thanks for the PR let's wait for other reviewers as well:+1:

**Comment by saketkumar95** [comment]
Instead of adding these pdfs why not writing up some good content of flask as `.md` file here? These pdfs can be found by 1 google search. No point that anyone will come up here and download the pdf.

**Comment by divyanshu-rawat** [comment]
ya, @saketkumar95 
I have even created a separate Cybros official blogging platform @ Medium https://medium.com/cybros-lnmiit but still, I would encourage to write a blog in GitHub and medium itself.
If we have to separate ourself from others then we have to provide relevant content that's what will help us in getting more folks and stars.
It would be great if we provide something that can't found by 1 google search.

**Comment by gauravkulkarni96** [comment]
yes.. all the codes we use in sessions and some reference material can be put in the repo and other blog kind of stuffs can be posted on medium.
In reference material, we will be adding some short notes or cheat sheets relevant to beginners.

**Comment by phunsukwangdu** [comment]
We do not want to use this repo as dropbox or google drive.

**Comment by phunsukwangdu** [comment]
@karantatiwala please make new branch when you send pull request :).

**Comment by divyanshu-rawat** [comment]
@phunsukwangdu I have already written guidelines here - https://github.com/Cybros/Lecture-Series-1-HTML-CSS-JS/wiki/Contribution-Guidelines

**Pull request closed without merging**
